from typing import Protocol, runtime_checkable

from harness.types import HealthReport, Message, Task, TaskResult


@runtime_checkable
class Worker(Protocol):
    agent_id:   str
    task_types: frozenset[str]

    async def start(self) -> None: ...
    async def stop(self)  -> None: ...
    async def execute(self, task: Task) -> TaskResult: ...
    async def health(self)           -> HealthReport: ...
    async def on_message(self, msg: Message) -> None: ...


@runtime_checkable
class Aggregator(Protocol):
    async def collect(self, result: TaskResult) -> None: ...
    async def flush(self) -> list[TaskResult]: ...
